# Generated by Django 3.1.7 on 2021-04-16 12:23
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bullet_weight', models.DecimalField(decimal_places=5, max_digits=8)),
                ('cx', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cannon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ammo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ammo')),
                ('cannon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cannon')),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('height', models.DecimalField(decimal_places=5, max_digits=8)),
                ('angle', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=5, max_digits=8)),
                ('standard_cannon_length', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('config', models.ManyToManyField(to='api.Config')),
                ('param_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.param')),
            ],
        ),
        migrations.CreateModel(
            name='InitSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_speed', models.DecimalField(decimal_places=5, max_digits=8)),
                ('ammo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ammo')),
                ('cannon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cannon')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='platform_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.platform'),
        ),
        migrations.AddField(
            model_name='cannon',
            name='ammo',
            field=models.ManyToManyField(through='api.InitSpeed', to='api.Ammo'),
        ),
    ]
