# Generated by Django 3.1.7 on 2021-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=64)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bullet_weight', models.IntegerField()),
                ('cx', models.IntegerField()),
            ],
        ),
    ]
