# Generated by Django 3.1.7 on 2021-03-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210305_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ammo',
            old_name='desc',
            new_name='name',
        ),
    ]
